'use strict';

const util = require('node:util');
const Support = require('../../../support');
const { DataTypes, Op, sql } = require('@sequelize/core');
const { OracleQuery } = require('@sequelize/oracle');
const { expect } = require('chai');

const expectsql = Support.expectsql;
const current = Support.sequelize;
const queryGenerator = current.dialect.queryGenerator;

if (current.dialect.name === 'oracle') {
  describe('[Oracle Specific] VECTOR', () => {
    describe('VECTOR datatype', () => {
      it('creates table with vector datatype', () => {
        const FooUser = current.define('user', {
          embedding: {
            type: DataTypes.VECTOR,
            allowNull: false,
          },
        });

        expectsql(
          queryGenerator.createTableQuery(
            FooUser.table,
            queryGenerator.attributesToSQL(FooUser.getAttributes()),
            {},
          ),
          {
            default: `BEGIN EXECUTE IMMEDIATE 'CREATE TABLE "users" ("id" NUMBER(*,0) GENERATED BY DEFAULT ON NULL AS IDENTITY, "embedding" VECTOR NOT NULL, "createdAt" TIMESTAMP WITH LOCAL TIME ZONE NOT NULL, "updatedAt" TIMESTAMP WITH LOCAL TIME ZONE NOT NULL,PRIMARY KEY ("id"))'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF; END;`,
          },
        );
      });
    });

    describe('VECTOR datatype with dimension and format', () => {
      it('creates table with vector datatype', () => {
        const FooUser = current.define('user', {
          embedding: {
            type: DataTypes.VECTOR(3, 'float32'),
            allowNull: false,
          },
        });

        expectsql(
          queryGenerator.createTableQuery(
            FooUser.table,
            queryGenerator.attributesToSQL(FooUser.getAttributes()),
            {},
          ),
          {
            default: `BEGIN EXECUTE IMMEDIATE 'CREATE TABLE "users" ("id" NUMBER(*,0) GENERATED BY DEFAULT ON NULL AS IDENTITY, "embedding" VECTOR(3, FLOAT32) NOT NULL, "createdAt" TIMESTAMP WITH LOCAL TIME ZONE NOT NULL, "updatedAt" TIMESTAMP WITH LOCAL TIME ZONE NOT NULL,PRIMARY KEY ("id"))'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF; END;`,
          },
        );
      });
    });

    describe('Vector index', () => {
      it('default', () => {
        expectsql(queryGenerator.addIndexQuery('Foo', ['vec1'], { type: 'VECTOR' }), {
          default:
            'CREATE VECTOR INDEX "foo_vec1" ON "Foo" ("vec1") ORGANIZATION INMEMORY NEIGHBOR GRAPH',
        });
      });

      it('accepts lowercase vector type', () => {
        expectsql(queryGenerator.addIndexQuery('Foo', ['vec1'], { type: 'vector' }), {
          default:
            'CREATE VECTOR INDEX "foo_vec1" ON "Foo" ("vec1") ORGANIZATION INMEMORY NEIGHBOR GRAPH',
        });
      });

      it('accepts object-form index definition with lowercase vector type', () => {
        expectsql(
          queryGenerator.addIndexQuery('Foo', {
            fields: ['vec1'],
            type: 'vector',
            using: 'ivf',
          }),
          {
            default:
              'CREATE VECTOR INDEX "foo_vec1" ON "Foo" ("vec1") ORGANIZATION NEIGHBOR PARTITION GRAPH',
          },
        );
      });

      it('ivf with parameters and target accuracy', () => {
        expectsql(
          queryGenerator.addIndexQuery('foo', ['vec1'], {
            type: 'VECTOR',
            using: 'ivf',
            accuracy: 95,
            parameter: { partitions: 5, samplesPerPartition: 10, minVectors: 10 },
          }),
          {
            default:
              'CREATE VECTOR INDEX "foo_vec1" ON "foo" ("vec1") ORGANIZATION NEIGHBOR PARTITION GRAPH WITH TARGET ACCURACY 95 PARAMETERS (type ivf, NEIGHBOR PARTITION 5, SAMPLES_PER_PARTITION 10, MIN_VECTORS_PER_PARTITION 10)',
          },
        );
      });

      it('supports explicit vector distance metric', () => {
        expectsql(
          queryGenerator.addIndexQuery('foo', ['vec1'], {
            type: 'VECTOR',
            distance: 'COSINE',
          }),
          {
            default:
              'CREATE VECTOR INDEX "foo_vec1" ON "foo" ("vec1") ORGANIZATION INMEMORY NEIGHBOR GRAPH WITH DISTANCE COSINE',
          },
        );
      });

      it('treats non-hnsw using as ivf organization', () => {
        expectsql(
          queryGenerator.addIndexQuery('foo', ['vec1'], {
            type: 'VECTOR',
            using: 'btree',
          }),
          {
            default:
              'CREATE VECTOR INDEX "foo_vec1" ON "foo" ("vec1") ORGANIZATION NEIGHBOR PARTITION GRAPH',
          },
        );
      });

      it('accepts uppercase using value', () => {
        expectsql(
          queryGenerator.addIndexQuery('foo', ['vec1'], {
            type: 'VECTOR',
            using: 'HNSW',
          }),
          {
            default:
              'CREATE VECTOR INDEX "foo_vec1" ON "foo" ("vec1") ORGANIZATION INMEMORY NEIGHBOR GRAPH',
          },
        );
      });

      it('accepts uppercase ivf using value', () => {
        expectsql(
          queryGenerator.addIndexQuery('foo', ['vec1'], {
            type: 'vector',
            using: 'IVF',
          }),
          {
            default:
              'CREATE VECTOR INDEX "foo_vec1" ON "foo" ("vec1") ORGANIZATION NEIGHBOR PARTITION GRAPH',
          },
        );
      });

      it('ignores ivf parameters when using hnsw', () => {
        expectsql(
          queryGenerator.addIndexQuery('foo', ['vec1'], {
            type: 'VECTOR',
            using: 'hnsw',
            parameter: { partitions: 4 },
          }),
          {
            default:
              'CREATE VECTOR INDEX "foo_vec1" ON "foo" ("vec1") ORGANIZATION INMEMORY NEIGHBOR GRAPH PARAMETERS (type hnsw)',
          },
        );
      });

      it('ignores hnsw parameters when using ivf', () => {
        expectsql(
          queryGenerator.addIndexQuery('foo', ['vec1'], {
            type: 'VECTOR',
            using: 'ivf',
            parameter: { neighbor: 8 },
          }),
          {
            default:
              'CREATE VECTOR INDEX "foo_vec1" ON "foo" ("vec1") ORGANIZATION NEIGHBOR PARTITION GRAPH PARAMETERS (type ivf)',
          },
        );
      });

      it('supports hnsw parameters in SQL', () => {
        expectsql(
          queryGenerator.addIndexQuery('foo', ['vec1'], {
            type: 'VECTOR',
            using: 'hnsw',
            parameter: { neighbor: 8, efconstruction: 32 },
          }),
          {
            default:
              'CREATE VECTOR INDEX "foo_vec1" ON "foo" ("vec1") ORGANIZATION INMEMORY NEIGHBOR GRAPH PARAMETERS (type hnsw, neighbor 8, efconstruction 32)',
          },
        );
      });

      it('supports ordered index fields', () => {
        expectsql(
          queryGenerator.addIndexQuery('foo', {
            fields: [{ name: 'vec1', order: 'DESC' }],
            type: 'VECTOR',
          }),
          {
            default:
              'CREATE VECTOR INDEX "foo_vec1" ON "foo" ("vec1" DESC) ORGANIZATION INMEMORY NEIGHBOR GRAPH',
          },
        );
      });

      it('supports SQL expression index fields', () => {
        expectsql(
          queryGenerator.addIndexQuery('foo', {
            name: 'foo_vec_expr',
            fields: [sql.literal('LOWER("vec1")')],
            type: 'VECTOR',
          }),
          {
            default:
              'CREATE VECTOR INDEX "foo_vec_expr" ON "foo" (LOWER("vec1")) ORGANIZATION INMEMORY NEIGHBOR GRAPH',
          },
        );
      });

      it('throws when no fields are provided', () => {
        expect(() => queryGenerator.addIndexQuery('foo', [], { type: 'VECTOR' })).to.throw(
          Error,
          'Vector indexes require at least one indexed field.',
        );
      });

      it('throws when a vector index field has no name', () => {
        expect(() =>
          queryGenerator.addIndexQuery('foo', {
            fields: [{}],
            type: 'VECTOR',
          }),
        ).to.throw(Error, 'The following index field has no name');
      });
    });

    describe('showIndex metadata', () => {
      const buildQuery = () => new OracleQuery({}, current, {});

      it('reports vector method hnsw', () => {
        const query = buildQuery();
        const rows = [
          {
            INDEX_NAME: 'IDX_HNSW',
            INDEX_TYPE: 'VECTOR',
            ITYP_NAME: null,
            UNIQUENESS: 'NONUNIQUE',
            CONSTRAINT_TYPE: null,
            TABLE_NAME: 'FOO',
            COLUMN_NAME: 'EMBEDDING',
            DESCEND: null,
            PARAMETERS_LOWER: 'type hnsw neighbor 10',
          },
        ];

        const result = query.handleShowIndexesQuery(rows);
        expect(result[0].method).to.equal('hnsw');
      });

      it('reports vector method ivf', () => {
        const query = buildQuery();
        const rows = [
          {
            INDEX_NAME: 'IDX_IVF',
            INDEX_TYPE: 'VECTOR',
            ITYP_NAME: null,
            UNIQUENESS: 'NONUNIQUE',
            CONSTRAINT_TYPE: null,
            TABLE_NAME: 'FOO',
            COLUMN_NAME: 'EMBEDDING',
            DESCEND: null,
            PARAMETERS_LOWER: 'type ivf neighbor partition 8',
          },
        ];

        const result = query.handleShowIndexesQuery(rows);
        expect(result[0].method).to.equal('ivf');
      });

      it('leaves method undefined when parameters missing', () => {
        const query = buildQuery();
        const rows = [
          {
            INDEX_NAME: 'IDX_UNKNOWN',
            INDEX_TYPE: 'VECTOR',
            ITYP_NAME: null,
            UNIQUENESS: 'NONUNIQUE',
            CONSTRAINT_TYPE: null,
            TABLE_NAME: 'FOO',
            COLUMN_NAME: 'EMBEDDING',
            DESCEND: null,
            PARAMETERS_LOWER: null,
          },
        ];

        const result = query.handleShowIndexesQuery(rows);
        expect(result[0].method).to.equal(undefined);
      });

      it('maps NORMAL index type to undefined', () => {
        const query = buildQuery();
        const rows = [
          {
            INDEX_NAME: 'IDX_NORMAL',
            INDEX_TYPE: 'NORMAL',
            ITYP_NAME: null,
            UNIQUENESS: 'NONUNIQUE',
            CONSTRAINT_TYPE: null,
            TABLE_NAME: 'FOO',
            COLUMN_NAME: 'ID',
            DESCEND: null,
            PARAMETERS_LOWER: null,
          },
        ];

        const result = query.handleShowIndexesQuery(rows);
        expect(result[0].type).to.equal(undefined);
      });

      it('keeps non-vector index types', () => {
        const query = buildQuery();
        const rows = [
          {
            INDEX_NAME: 'IDX_BITMAP',
            INDEX_TYPE: 'BITMAP',
            ITYP_NAME: null,
            UNIQUENESS: 'NONUNIQUE',
            CONSTRAINT_TYPE: null,
            TABLE_NAME: 'FOO',
            COLUMN_NAME: 'ID',
            DESCEND: null,
            PARAMETERS_LOWER: null,
          },
        ];

        const result = query.handleShowIndexesQuery(rows);
        expect(result[0].type).to.equal('BITMAP');
      });
    });

    describe('VECTOR datatype override hooks', () => {
      it('converts array input to Float64Array bind values', () => {
        const type = DataTypes.VECTOR(3).toDialectDataType(current.dialect);
        const bindValue = type.toBindableValue([1, 2, 3]);

        expect(bindValue).to.be.instanceOf(Float64Array);
        expect(Array.from(bindValue)).to.deep.equal([1, 2, 3]);
      });

      it('keeps typed array input as-is for binding', () => {
        const type = DataTypes.VECTOR(3).toDialectDataType(current.dialect);
        const typed = new Float32Array([1, 2, 3]);

        expect(type.toBindableValue(typed)).to.equal(typed);
      });

      it('returns the Oracle VECTOR bind definition', () => {
        const type = DataTypes.VECTOR(3).toDialectDataType(current.dialect);

        expect(type._getBindDef({ DB_TYPE_VECTOR: 'DB_TYPE_VECTOR' })).to.deep.equal({
          type: 'DB_TYPE_VECTOR',
        });
      });
    });

    describe('Vector where clause', () => {
      const queryVector = [1, 2, 3];

      const testsql = function (key, value, options, expectation) {
        if (expectation === undefined) {
          expectation = options;
          options = undefined;
        }

        const whereObj = sql.where(key, value);
        it(
          util.inspect(whereObj, { depth: 4 }) + (options ? `, ${util.inspect(options)}` : ''),
          () => {
            return expectsql(queryGenerator.whereItemsQuery(whereObj, options), expectation);
          },
        );
      };

      testsql(
        sql.fn('VECTOR_DISTANCE', sql.attribute('embedding'), queryVector),
        {
          [Op.lt]: 2,
        },
        {
          oracle: `VECTOR_DISTANCE("embedding", VECTOR('[1,2,3]')) < 2`,
        },
      );

      testsql(
        sql.fn('VECTOR_DISTANCE', sql.attribute('embedding'), new Float32Array([1, 2, 3])),
        {
          [Op.lt]: 2,
        },
        {
          oracle: `VECTOR_DISTANCE("embedding", VECTOR('[1,2,3]')) < 2`,
        },
      );

      testsql(
        sql.fn('VECTOR_DISTANCE', sql.attribute('embedding'), `VECTOR('[1,2,3]')`),
        {
          [Op.lt]: 2,
        },
        {
          oracle: `VECTOR_DISTANCE("embedding", VECTOR('[1,2,3]')) < 2`,
        },
      );

      testsql(
        sql.fn('VECTOR_DISTANCE', sql.attribute('embedding'), new Uint8Array([1, 2, 3])),
        {
          [Op.lt]: 2,
        },
        {
          oracle: `VECTOR_DISTANCE("embedding", VECTOR('[1,2,3]')) < 2`,
        },
      );

      it('throws when second argument is not a vector input', () => {
        expect(() =>
          queryGenerator.whereItemsQuery(
            sql.where(sql.fn('VECTOR_DISTANCE', sql.attribute('embedding'), 'not-a-vector'), {
              [Op.lt]: 2,
            }),
          ),
        ).to.throw(Error, 'Invalid value received for the "where" option');
      });

      it('throws for malformed VECTOR literal strings', () => {
        expect(() =>
          queryGenerator.whereItemsQuery(
            sql.where(sql.fn('VECTOR_DISTANCE', sql.attribute('embedding'), `VECTR('[1,2,3]')`), {
              [Op.lt]: 2,
            }),
          ),
        ).to.throw(Error, 'Invalid value received for the "where" option');
      });

      it('throws for malformed VECTOR literal payloads', () => {
        expect(() =>
          queryGenerator.whereItemsQuery(
            sql.where(
              sql.fn('VECTOR_DISTANCE', sql.attribute('embedding'), `VECTOR('[1,foo,3]')`),
              {
                [Op.lt]: 2,
              },
            ),
          ),
        ).to.throw(Error, 'Invalid value received for the "where" option');
      });

      it('throws when vector function has too few arguments', () => {
        expect(() =>
          queryGenerator.formatSqlExpression(sql.fn('VECTOR_DISTANCE', sql.attribute('embedding'))),
        ).to.throw(Error, 'VECTOR_DISTANCE expects exactly 2 arguments');
      });

      it('throws when vector function has too many arguments', () => {
        expect(() =>
          queryGenerator.formatSqlExpression(
            sql.fn('VECTOR_DISTANCE', sql.attribute('embedding'), [1, 2, 3], [4, 5, 6]),
          ),
        ).to.throw(Error, 'VECTOR_DISTANCE expects exactly 2 arguments');
      });
    });

    describe('order by distance with limit', () => {
      const queryVector = [1, 2, 3, 4];

      const User = Support.sequelize.define(
        'User',
        {
          embedding: {
            type: DataTypes.VECTOR(4),
          },
        },
        {
          tableName: 'user',
        },
      );

      it('generates order by vector distance', () => {
        expectsql(
          queryGenerator.selectQuery(
            User.table,
            {
              model: User,
              attributes: ['embedding'],
              order: [sql.fn('VECTOR_DISTANCE', sql.attribute('embedding'), queryVector)],
              limit: 5,
            },
            User,
          ),
          {
            oracle: `SELECT "embedding" FROM "user" "User" ORDER BY VECTOR_DISTANCE("embedding", VECTOR('[1,2,3,4]')) OFFSET 0 ROWS FETCH NEXT 5 ROWS ONLY;`,
          },
        );
      });
    });
  });
}
