'use strict';

const util = require('node:util');
const Support = require('../../../support');
const { DataTypes, Op, sql } = require('@sequelize/core');

const expectsql = Support.expectsql;
const current = Support.sequelize;
const queryGenerator = current.dialect.queryGenerator;

if (current.dialect.name === 'oracle') {
  describe('[Oracle Specific] VECTOR', () => {
    describe('VECTOR datatype', () => {
      it('creates table with vector datatype', () => {
        const FooUser = current.define('user', {
          embedding: {
            type: DataTypes.VECTOR,
            allowNull: false,
          },
        });

        expectsql(
          queryGenerator.createTableQuery(
            FooUser.table,
            queryGenerator.attributesToSQL(FooUser.getAttributes()),
            {},
          ),
          {
            default: `BEGIN EXECUTE IMMEDIATE 'CREATE TABLE "users" ("id" NUMBER(*,0) GENERATED BY DEFAULT ON NULL AS IDENTITY, "embedding" VECTOR NOT NULL, "createdAt" TIMESTAMP WITH LOCAL TIME ZONE NOT NULL, "updatedAt" TIMESTAMP WITH LOCAL TIME ZONE NOT NULL,PRIMARY KEY ("id"))'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF; END;`,
          },
        );
      });
    });

    describe('VECTOR datatype with dimension and format', () => {
      it('creates table with vector datatype', () => {
        const FooUser = current.define('user', {
          embedding: {
            type: DataTypes.VECTOR(3, 'float32'),
            allowNull: false,
          },
        });

        expectsql(
          queryGenerator.createTableQuery(
            FooUser.table,
            queryGenerator.attributesToSQL(FooUser.getAttributes()),
            {},
          ),
          {
            default: `BEGIN EXECUTE IMMEDIATE 'CREATE TABLE "users" ("id" NUMBER(*,0) GENERATED BY DEFAULT ON NULL AS IDENTITY, "embedding" VECTOR(3, FLOAT32) NOT NULL, "createdAt" TIMESTAMP WITH LOCAL TIME ZONE NOT NULL, "updatedAt" TIMESTAMP WITH LOCAL TIME ZONE NOT NULL,PRIMARY KEY ("id"))'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF; END;`,
          },
        );
      });
    });

    describe('Vector index', () => {
      it('default', () => {
        expectsql(queryGenerator.addIndexQuery('Foo', ['vec1'], { type: 'VECTOR' }), {
          default:
            'CREATE VECTOR INDEX "foo_vec1" ON "Foo" ("vec1") ORGANIZATION INMEMORY NEIGHBOR GRAPH',
        });
      });

      it('ivf with parameters and target accuracy', () => {
        expectsql(
          queryGenerator.addIndexQuery('foo', ['vec1'], {
            type: 'VECTOR',
            using: 'ivf',
            accuracy: 95,
            parameter: { partitions: 5, samplesPerPartition: 10, minVectors: 10 },
          }),
          {
            default:
              'CREATE VECTOR INDEX "foo_vec1" ON "foo" ("vec1") ORGANIZATION NEIGHBOR PARTITION GRAPH WITH TARGET ACCURACY 95 PARAMETERS (type ivf, NEIGHBOR PARTITION 5, SAMPLES_PER_PARTITION 10, MIN_VECTORS_PER_PARTITION 10)',
          },
        );
      });
    });

    describe('Vector where clause', () => {
      const queryVector = [1, 2, 3];

      const testsql = function (key, value, options, expectation) {
        if (expectation === undefined) {
          expectation = options;
          options = undefined;
        }

        it(`${String(key)}: ${util.inspect(value, { depth: 10 })}${options ? `, ${util.inspect(options)}` : ''}`, () => {
          return expectsql(
            queryGenerator.whereItemsQuery(sql.where(key, value), options),
            expectation,
          );
        });
      };

      testsql(
        sql.fn('VECTOR_DISTANCE', sql.attribute('embedding'), queryVector),
        {
          [Op.lt]: 2,
        },
        {
          oracle: `VECTOR_DISTANCE("embedding", VECTOR('[1,2,3]')) < 2`,
        },
      );
    });

    describe('order by distance with limit', () => {
      const queryVector = [1, 2, 3, 4];

      const User = Support.sequelize.define(
        'User',
        {
          embedding: {
            type: DataTypes.VECTOR(4),
          },
        },
        {
          tableName: 'user',
        },
      );

      it('generates order by vector distance', () => {
        expectsql(
          queryGenerator.selectQuery(
            User.table,
            {
              model: User,
              attributes: ['embedding'],
              order: [sql.fn('VECTOR_DISTANCE', sql.attribute('embedding'), queryVector)],
              limit: 5,
            },
            User,
          ),
          {
            oracle: `SELECT "embedding" FROM "user" "User" ORDER BY VECTOR_DISTANCE("embedding", VECTOR('[1,2,3,4]')) OFFSET 0 ROWS FETCH NEXT 5 ROWS ONLY;`,
          },
        );
      });
    });
  });
}
